Repository LorenzoGallizioli/WireShield, pull requests merged in 2024-12, with the labels that each got.

#15 Updates docs+create offical doc of wire shield+create sequence diagram
  ProjectPlan.md
  docs/AnalisiFattibilità.md
  docs/LineeGuida.md
  docs/SprintBacklog.md
  docs/WireShield.md
  docs/activity_diagram/activity_diagram.jpg
  docs/sequence_diagram/sequence_diagram.jpg
Labels: documentation, feature

#20 14-diagramma-delle-classi-+-generazione-struttura
  docs/ClassDiagram/ClassDiagram.di
  docs/ClassDiagram/ClassDiagram.notation
  docs/ClassDiagram/ClassDiagram.png
  docs/ClassDiagram/ClassDiagram.uml
  docs/ClassDiagram/ClassDiagram_it_IT.properties
  docs/ClassDiagram/WorkFlow.md
Labels: documentation, feature

#18 create communication diagram
  docs/CommunicationDiagram/CommunicationWireShield.di
  docs/CommunicationDiagram/CommunicationWireShield.notation
  docs/CommunicationDiagram/CommunicationWireShield.png
  docs/CommunicationDiagram/CommunicationWireShield.uml
Labels: documentation

#24 14-creazione-struttura-from-class-diagram
  src/main/java/com/wireshield/UI/MainUI.java
  src/main/java/com/wireshield/UI/SettingsUI.java
  src/main/java/com/wireshield/av/AVInterface.java
  src/main/java/com/wireshield/av/AntivirusManager.java
  src/main/java/com/wireshield/av/ClamAV.java
  src/main/java/com/wireshield/av/ScanReport.java
  src/main/java/com/wireshield/av/VirusTotal.java
  src/main/java/com/wireshield/clamav/ClamAVScanner.java
  src/main/java/com/wireshield/enums/connectionStates.java
  src/main/java/com/wireshield/enums/runningStates.java
  src/main/java/com/wireshield/enums/vpnOperations.java
  src/main/java/com/wireshield/enums/warningClass.java
  src/main/java/com/wireshield/localfileutils/DownloadManager.java
  src/main/java/com/wireshield/localfileutils/File.java
  src/main/java/com/wireshield/localfileutils/SystemOrchestrator.java
  src/main/java/com/wireshield/ui/UserInterface.java
  src/main/java/com/wireshield/virustotal/VirusTotalScanner.java
  src/main/java/com/wireshield/wireguard/Connection.java
  src/main/java/com/wireshield/wireguard/Peer.java
  src/main/java/com/wireshield/wireguard/PeerManager.java
  src/main/java/com/wireshield/wireguard/WireGuardConnector.java
  src/main/java/com/wireshield/wireguard/WireguardManager.java
Labels: feature

#26 add junit test classes
  pom.xml
  src/test/java/com/wireshield/MainTest.java
  src/test/java/com/wireshield/av/AntivirusManagerTest.java
  src/test/java/com/wireshield/av/ClamAVTest.java
  src/test/java/com/wireshield/av/ScanReportTest.java
  src/test/java/com/wireshield/av/VirusTotalTest.java
  src/test/java/com/wireshield/enums/connectionStatesTest.java
  src/test/java/com/wireshield/enums/runningStatesTest.java
  src/test/java/com/wireshield/enums/vpnOperationsTest.java
  src/test/java/com/wireshield/enums/warningClassTest.java
  src/test/java/com/wireshield/localfileutils/DownloadManagerTest.java
  src/test/java/com/wireshield/localfileutils/FileTest.java
  src/test/java/com/wireshield/localfileutils/SystemOrchestratorTest.java
  src/test/java/com/wireshield/ui/UserInterfaceTest.java
  src/test/java/com/wireshield/wireguard/ConnectionTest.java
  src/test/java/com/wireshield/wireguard/PeerManagerTest.java
  src/test/java/com/wireshield/wireguard/PeerTest.java
  src/test/java/com/wireshield/wireguard/WireguardManagerTest.java
Labels: feature

#23 22-convert-diagrams-in-papyrus
  docs/ActivityDiagram/activityDiagram.jpg
  docs/SequenceDiagram/sequenceDiagram.jpg
  docs/activityDiagram/activityDiagram.di
  docs/activityDiagram/activityDiagram.jpg
  docs/activityDiagram/activityDiagram.notation
  docs/activityDiagram/activityDiagram.uml
  docs/sequenceDiagram/SequenceDiagram.di
  docs/sequenceDiagram/SequenceDiagram.notation
  docs/sequenceDiagram/SequenceDiagram.uml
  docs/sequenceDiagram/sequenceDiagram.png
Labels: refactoring

#37 36 Add log4j2
  resources/api_keys.properties
  resources/config/wireguard.conf
  src/main/java/com/wireshield/Main.java
  src/main/resources/log4j2.xml
Labels: feature

#35 Implementazione classi wireguardmanager & connection
  src/main/java/com/wireshield/Main.java
  src/main/java/com/wireshield/localfileutils/SystemOrchestrator.java
  src/main/java/com/wireshield/wireguard/Connection.java
  src/main/java/com/wireshield/wireguard/WireguardManager.java
  src/test/java/com/wireshield/wireguard/ConnectionTest.java
  src/test/java/com/wireshield/wireguard/WireguardManagerTest.java
Labels: feature

#39 30 implementazione classi downloadmonitor file
  pom.xml
  src/main/java/com/wireshield/av/AntivirusManager.java
  src/main/java/com/wireshield/av/ClamAV.java
  src/main/java/com/wireshield/av/ScanReport.java
  src/main/java/com/wireshield/av/VirusTotal.java
  src/main/java/com/wireshield/localfileutils/DownloadManager.java
  src/main/java/com/wireshield/localfileutils/SystemOrchestrator.java
  src/test/java/com/wireshield/MainTest.java
  src/test/java/com/wireshield/av/AntivirusManagerTest.java
  src/test/java/com/wireshield/av/ScanReportTest.java
  src/test/java/com/wireshield/localfileutils/DownloadManagerTest.java
  src/test/java/com/wireshield/localfileutils/FileTest.java
  src/test/java/com/wireshield/localfileutils/SystemOrchestratorTest.java
Labels: feature

#40 30 implementazione classi downloadmonitor file
  pom.xml
  src/main/java/com/wireshield/av/AntivirusManager.java
  src/main/java/com/wireshield/av/ClamAV.java
  src/main/java/com/wireshield/av/ScanReport.java
  src/main/java/com/wireshield/av/VirusTotal.java
  src/main/java/com/wireshield/localfileutils/DownloadManager.java
  src/main/java/com/wireshield/localfileutils/SystemOrchestrator.java
  src/test/java/com/wireshield/MainTest.java
  src/test/java/com/wireshield/av/AntivirusManagerTest.java
  src/test/java/com/wireshield/av/ScanReportTest.java
  src/test/java/com/wireshield/localfileutils/DownloadManagerTest.java
  src/test/java/com/wireshield/localfileutils/FileTest.java
  src/test/java/com/wireshield/localfileutils/SystemOrchestratorTest.java
Labels: feature

#42 Implementazione ClamAV + testing + commenti e javaDOC + cancellazioni metodi duplicati in DownloadManager
  pom.xml
  src/main/java/com/wireshield/Main.java
  src/main/java/com/wireshield/av/AVInterface.java
  src/main/java/com/wireshield/av/AntivirusManager.java
  src/main/java/com/wireshield/av/ClamAV.java
  src/main/java/com/wireshield/av/ScanReport.java
  src/main/java/com/wireshield/av/VirusTotal.java
  src/main/java/com/wireshield/localfileutils/DownloadManager.java
  src/main/java/com/wireshield/localfileutils/FileManager.java
  src/main/java/com/wireshield/localfileutils/SystemOrchestrator.java
  src/main/java/com/wireshield/ui/UserInterface.java
  src/test/java/com/wireshield/av/AntivirusManagerTest.java
  src/test/java/com/wireshield/av/ClamAVTest.java
  src/test/java/com/wireshield/av/ScanReportTest.java
  src/test/java/com/wireshield/av/VirusTotalTest.java
  src/test/java/com/wireshield/localfileutils/DownloadManagerTest.java
  src/test/java/com/wireshield/localfileutils/FileManagerTest.java
  src/test/java/com/wireshield/localfileutils/SystemOrchestratorTest.java
Labels: feature

#54 53-modifica-classe-virustotal-introducendo-json
  api_key.txt
  config/api_key.txt
  config/config.json
  src/main/java/com/wireshield/av/FileManager.java
  src/main/java/com/wireshield/av/VirusTotal.java
  src/test/java/com/wireshield/av/AntivirusManagerTest.java
  src/test/java/com/wireshield/av/FileManagerTest.java
  src/test/java/com/wireshield/av/VirusTotalTest.java
Labels: feature, refactoring
