Repository LorenzoGallizioli/WireShield, pull requests merged in 2025-01, with the labels that each got.

#58 56-implementazione-metodo-per-aggiornamento-log-wg
  config/config.json
  config/connection-configurations/testPeer.conf
  config/logDump.txt
  pom.xml
  src/main/java/com/wireshield/av/ClamAV.java
  src/main/java/com/wireshield/wireguard/Connection.java
  src/main/java/com/wireshield/wireguard/WireguardManager.java
  src/test/java/com/wireshield/wireguard/ConnectionTest.java
  src/test/java/com/wireshield/wireguard/WireguardManagerTest.java
Labels: feature

#64 62-aumentare-copertura-test-wireguard
  src/main/java/com/wireshield/wireguard/Peer.java
  src/main/java/com/wireshield/wireguard/PeerManager.java
  src/main/java/com/wireshield/wireguard/WireguardManager.java
  src/test/java/com/wireshield/wireguard/PeerManagerTest.java
  src/test/java/com/wireshield/wireguard/WireguardManagerTest.java
Labels: refactoring

#68 Update package av-localfiles-enums
  wireshield/src/main/java/com/wireshield/av/AntivirusManager.java
  wireshield/src/main/java/com/wireshield/av/ClamAV.java
  wireshield/src/main/java/com/wireshield/av/FileManager.java
  wireshield/src/main/java/com/wireshield/av/VirusTotal.java
  wireshield/src/main/java/com/wireshield/localfileutils/SystemOrchestrator.java
  wireshield/src/main/java/com/wireshield/wireguard/WireguardManager.java
  wireshield/src/test/java/com/wireshield/av/AntivirusManagerTest.java
  wireshield/src/test/java/com/wireshield/av/ClamAVTest.java
  wireshield/src/test/java/com/wireshield/av/FileManagerTest.java
  wireshield/src/test/java/com/wireshield/av/ScanReportTest.java
  wireshield/src/test/java/com/wireshield/av/VirusTotalTest.java
  wireshield/src/test/java/com/wireshield/enums/connectionStatesTest.java
  wireshield/src/test/java/com/wireshield/enums/runningStatesTest.java
  wireshield/src/test/java/com/wireshield/enums/vpnOperationsTest.java
  wireshield/src/test/java/com/wireshield/enums/warningClassTest.java
  wireshield/src/test/java/com/wireshield/localfileutils/DownloadManagerTest.java
  wireshield/src/test/java/com/wireshield/localfileutils/SystemOrchestratorTest.java
  wireshield/src/test/java/com/wireshield/wireguard/WireguardManagerTest.java
Labels: feature, refactoring

#80 76-definizione-momenti-di-aggionamento-dei-log
  wireshield/src/main/java/com/wireshield/ui/UserInterface.java
Labels: bug

#84 82-sistemare-isrunningasadmin-nella-classe-main
  wireshield/src/main/java/com/wireshield/Main.java
Labels: bug

#73 72-implementazione-test-userinterface
  wireshield/src/main/java/com/wireshield/ui/UserInterface.java
  wireshield/src/test/java/com/wireshield/ui/UserInterfaceTest.java
Labels: feature

#85 81-aggiungere-stato-connessione-allinterfaccia-utente
  wireshield/src/main/java/com/wireshield/ui/UserInterface.java
  wireshield/src/main/java/com/wireshield/wireguard/Connection.java
  wireshield/src/main/java/com/wireshield/wireguard/WireguardManager.java
  wireshield/src/main/resources/com/wireshield/ui/MainView.fxml
  wireshield/src/test/java/com/wireshield/ui/UserInterfaceTest.java
Labels: feature

#86 modify class diagram for UserInterface and WireGuardManager
  docs/ClassDiagram/ClassDiagram.notation
  docs/ClassDiagram/ClassDiagram.png
  docs/ClassDiagram/ClassDiagram.uml
  docs/ClassDiagram/ClassDiagram_it_IT.properties
Labels: documentation

#78 77-sistemazione-codice-con-sonarlint
  wireshield/config/config.json
  wireshield/pom.xml
  wireshield/src/main/java/com/wireshield/av/AntivirusManager.java
  wireshield/src/main/java/com/wireshield/av/ClamAV.java
  wireshield/src/main/java/com/wireshield/av/FileManager.java
  wireshield/src/main/java/com/wireshield/av/ScanReport.java
  wireshield/src/main/java/com/wireshield/av/VirusTotal.java
  wireshield/src/main/java/com/wireshield/localfileutils/DownloadManager.java
  wireshield/src/main/java/com/wireshield/localfileutils/SystemOrchestrator.java
  wireshield/src/main/java/com/wireshield/ui/UserInterface.java
  wireshield/src/main/java/com/wireshield/wireguard/Connection.java
  wireshield/src/main/java/com/wireshield/wireguard/Peer.java
  wireshield/src/main/java/com/wireshield/wireguard/PeerManager.java
  wireshield/src/main/java/com/wireshield/wireguard/WireguardManager.java
  wireshield/src/test/java/com/wireshield/MainTest.java
  wireshield/src/test/java/com/wireshield/av/AntivirusManagerTest.java
  wireshield/src/test/java/com/wireshield/av/ClamAVTest.java
  wireshield/src/test/java/com/wireshield/av/FileManagerTest.java
  wireshield/src/test/java/com/wireshield/av/VirusTotalTest.java
  wireshield/src/test/java/com/wireshield/enums/TestConnectionStates.java
  wireshield/src/test/java/com/wireshield/enums/TestRunningStates.java
  wireshield/src/test/java/com/wireshield/enums/TestVpnOperations.java
  wireshield/src/test/java/com/wireshield/enums/TestWarningClass.java
  wireshield/src/test/java/com/wireshield/localfileutils/DownloadManagerTest.java
  wireshield/src/test/java/com/wireshield/localfileutils/SystemOrchestratorTest.java
  wireshield/src/test/java/com/wireshield/ui/UserInterfaceTest.java
  wireshield/src/test/java/com/wireshield/wireguard/ConnectionTest.java
  wireshield/src/test/java/com/wireshield/wireguard/PeerManagerTest.java
  wireshield/src/test/java/com/wireshield/wireguard/WireguardManagerTest.java
Labels: refactoring

#75 74-creare-thread-concorrente-per-lanalisi-costante-dello-stato-dei-servizi
  wireshield/src/main/java/com/wireshield/av/AntivirusManager.java
  wireshield/src/main/java/com/wireshield/av/VirusTotal.java
  wireshield/src/main/java/com/wireshield/localfileutils/DownloadManager.java
  wireshield/src/main/java/com/wireshield/localfileutils/SystemOrchestrator.java
  wireshield/src/main/java/com/wireshield/ui/UserInterface.java
  wireshield/src/test/java/com/wireshield/localfileutils/DownloadManagerTest.java
  wireshield/src/test/java/com/wireshield/localfileutils/SystemOrchestratorTest.java
Labels: feature

#91 88-log-wireguard-non-funzionanti
  .gitignore
  wireshield/config/logDump.txt
  wireshield/src/main/java/com/wireshield/ui/UserInterface.java
  wireshield/src/main/java/com/wireshield/wireguard/WireguardManager.java
  wireshield/src/test/java/com/wireshield/wireguard/WireguardManagerTest.java
Labels: bug

#93 92-bottone-avvia-vpn-sbloccato
  wireshield/src/main/java/com/wireshield/ui/UserInterface.java
Labels: bug

#90 fix class diagram
  docs/ClassDiagram/ClassDiagram.notation
  docs/ClassDiagram/ClassDiagram.png
  docs/ClassDiagram/ClassDiagram.uml
  docs/ClassDiagram/ClassDiagram_it_IT.properties
Labels: bug, documentation

#89 87-sistemare-commenti-e-javadoc-di-tutte-le-classi-del-progetto
  wireshield/src/main/java/com/wireshield/Main.java
  wireshield/src/main/java/com/wireshield/av/AVInterface.java
  wireshield/src/main/java/com/wireshield/av/AntivirusManager.java
  wireshield/src/main/java/com/wireshield/av/ClamAV.java
  wireshield/src/main/java/com/wireshield/av/FileManager.java
  wireshield/src/main/java/com/wireshield/av/ScanReport.java
  wireshield/src/main/java/com/wireshield/av/VirusTotal.java
  wireshield/src/main/java/com/wireshield/enums/connectionStates.java
  wireshield/src/main/java/com/wireshield/enums/runningStates.java
  wireshield/src/main/java/com/wireshield/enums/vpnOperations.java
  wireshield/src/main/java/com/wireshield/enums/warningClass.java
  wireshield/src/main/java/com/wireshield/localfileutils/DownloadManager.java
  wireshield/src/main/java/com/wireshield/localfileutils/SystemOrchestrator.java
  wireshield/src/main/java/com/wireshield/ui/UserInterface.java
  wireshield/src/main/java/com/wireshield/wireguard/Connection.java
  wireshield/src/main/java/com/wireshield/wireguard/Peer.java
  wireshield/src/main/java/com/wireshield/wireguard/PeerManager.java
  wireshield/src/main/java/com/wireshield/wireguard/WireguardManager.java
  wireshield/src/test/java/com/wireshield/av/AntivirusManagerTest.java
  wireshield/src/test/java/com/wireshield/av/ClamAVTest.java
  wireshield/src/test/java/com/wireshield/av/FileManagerTest.java
  wireshield/src/test/java/com/wireshield/av/ScanReportTest.java
  wireshield/src/test/java/com/wireshield/av/VirusTotalTest.java
  wireshield/src/test/java/com/wireshield/enums/TestConnectionStates.java
  wireshield/src/test/java/com/wireshield/enums/TestRunningStates.java
  wireshield/src/test/java/com/wireshield/enums/TestVpnOperations.java
  wireshield/src/test/java/com/wireshield/enums/TestWarningClass.java
  wireshield/src/test/java/com/wireshield/localfileutils/DownloadManagerTest.java
  wireshield/src/test/java/com/wireshield/localfileutils/SystemOrchestratorTest.java
  wireshield/src/test/java/com/wireshield/ui/UserInterfaceTest.java
  wireshield/src/test/java/com/wireshield/wireguard/ConnectionTest.java
  wireshield/src/test/java/com/wireshield/wireguard/PeerManagerTest.java
  wireshield/src/test/java/com/wireshield/wireguard/PeerTest.java
  wireshield/src/test/java/com/wireshield/wireguard/WireguardManagerTest.java
Labels: refactoring

#96 95-aggiungere-la-possibilità-di-spostare-la-finestra-nello-spazio
  wireshield/src/main/java/com/wireshield/ui/UserInterface.java
Labels: feature

#97 94-correggere-uso-errato-di-threadcurrentthreadisinterrupted-e-interruptedexception
  wireshield/src/main/java/com/wireshield/av/AntivirusManager.java
  wireshield/src/main/java/com/wireshield/av/VirusTotal.java
  wireshield/src/main/java/com/wireshield/localfileutils/DownloadManager.java
  wireshield/src/main/java/com/wireshield/localfileutils/SystemOrchestrator.java
  wireshield/src/main/java/com/wireshield/wireguard/WireguardManager.java
Labels: bug

#101 100-fix-userinterface-tests
  wireshield/src/test/java/com/wireshield/ui/UserInterfaceTest.java
Labels: bug
